DROP TABLE IF EXISTS Spins;
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Donors;
DROP TABLE IF EXISTS Records;
DROP TABLE IF EXISTS AlbumGenres;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Credits;
DROP TABLE IF EXISTS Songs;
DROP TABLE IF EXISTS Albums;
DROP TABLE IF EXISTS Memberships;
DROP TABLE IF EXISTS Artists;
DROP TABLE IF EXISTS Bands;

